workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/appvivavoz.xcworkspace"
        XCODE_SCHEME: "appvivavoz"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build
    artifacts:
      - build/Build/Products/Release-iphoneos/*.app
      - build/Build/Products/Release-iphoneos/*.ipa
