require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'appvivavoz' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # If you're using autolinking, this line might not be needed
  pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'

  # NOTE: Do not remove, needed to keep WatermelonDB compiling:
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true

  # NOTE: This is required as of v0.23
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true

  target 'appvivavozTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  use_flipper!({'Flipper' => '0.140.0', 'Flipper-Folly' => '2.6.7'})
  post_install do |installer|
    flipper_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end

  end
end

target 'appvivavoz-tvOS' do
  # Pods for appvivavoz-tvOS

  target 'appvivavoz-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end
